### FORMS

form_2015_2p <- read_csv("ECE/Otros/Primaria/ECE2015_2P_Cuestionario_Padres de familia.csv", locale = locale(decimal_mark = ","), guess_max = 15000)
form_2016_2p <- read_csv("ECE/Otros/Primaria/ECE2016_2P_Cuestionario_Padres de familia.csv", na = "#NULL!", locale = locale(decimal_mark = ","))
form_2016_4p <- read_csv("ECE/Otros/Primaria/ECE2016_4P_Cuestionario_Padres de familia.csv", na = "#NULL!", locale = locale(decimal_mark = ","))
form_2018_4p <- read_csv("ECE/Otros/Primaria/ECE2018_4P_Cuestionario_Padres de familia.csv", na = "#NULL!", locale = locale(decimal_mark = ","))
form_2015_2s <- read_csv("ECE/Otros/2do de Secundaria/Cuestionario/ECE2015_2S_Cuestionario.csv", na = "#NULL!", locale = locale(decimal_mark = ","))
form_2016_2s <- read_csv("ECE/Otros/2do de Secundaria/Cuestionario/ECE2016_2S_Cuestionario.csv", na = "#NULL!", locale = locale(decimal_mark = ","))
form_2018_2s <- read_csv("ECE/Otros/2do de Secundaria/Cuestionario/ECE2018_2S_Cuestionario.csv", na = "#NULL!", locale = locale(decimal_mark = ","))

## ECE 2015
# 2do de primaria

form_2015_2p %<>%
  rename(
    cod_est = cod_al,
    guardian = pfp01,
    age.mother = pfp02,
    idioma_nativo.mother = pfp03,
    idioma_hogar.mother = pfp04,
    education.mother = pfp05,
    age.father = pfp06,
    idioma_nativo.father = pfp07,
    idioma_hogar.father = pfp08,
    education.father = pfp09,
    hogar.mother = pfp10_1,
    hogar.father = pfp10_2,
    hogar.abuelos = pfp10_3,
    hogar.hermanos = pfp10_4,
    hogar.tios = pfp10_5,
    hogar.familiares = pfp10_6,
    hogar.nofamiliares = pfp10_7,
    n.hermanos = pfp11,
    n.dependientes = pfp12,
    household.size = pfp13,
    household.rooms = pfp14,
    income = pfp15,
    ise_house.wall = pfp16,
    ise_house.roof = pfp17,
    ise_house.floor = pfp18,
    ise_utilities.water = pfp19,
    ise_utilities.sewage = pfp20,
    ise_utilities.light = pfp21,
    cocina = pfp22,
    ise_assets.radio = pfp23_01,
    ise_assets.licuadora = pfp23_02,
    ise_assets.plancha = pfp23_03,
    ise_assets.tv = pfp23_04,
    ise_other.tv_cc = pfp23_05,
    ise_assets.reproductor = pfp23_06,
    ise_other.telefono = pfp23_07,
    ise_assets.celular = pfp23_08,
    ise_other.datos_moviles = pfp23_09,
    ise_other.internet = pfp23_10,
    ise_assets.pc = pfp23_11,
    ise_assets.laptop = pfp23_12,
    ise_assets.tablet = pfp23_13,
    ise_assets.sonido = pfp23_14,
    ise_assets.consola = pfp23_15,
    ise_assets.microondas = pfp23_16,
    ise_assets.refigerador = pfp23_17,
    ise_assets.lavadora = pfp23_18,
    ise_assets.moto = pfp23_19,
    ise_assets.auto = pfp23_20,
    drop_ise_assets.camioneta = pfp23_21,
    uso.moto = pfp24_1,
    uso.auto = pfp24_2,
    uso.camioneta = pfp24_3,
    servicio.periodico = pfp25_1,
    servicio.asociacion = pfp25_2,
    servicio.seguro = pfp25_3,
    ayuda.juntos = pfp26_1,
    ayuda.pension65 = pfp26_2,
    ayuda.comedor = pfp26_3,
    ayuda.sis = pfp26_4,
    ayuda.vasodeleche = pfp26_5,
    books.n = pfp27,
    books.school = pfp28_1,
    books.encyclopedia = pfp28_2,
    books.specialized = pfp28_3,
    books.literature = pfp28_4,
    estudio.espacio = pfp29,
    estudio.tranquilo = pfp30_1,
    estudio.luz = pfp30_2,
    estudio.muebles = pfp30_3,
    estudio.estante = pfp30_4,
    estudio.pc = pfp30_5,
    involvement_direct.homework_speak = pfp31_01,
    involvement_direct.homework_help = pfp31_02,
    involvement_direct.homework_explain = pfp31_03,
    involvement_direct.advice_books = pfp31_04,
    involvement_direct.advice_performance = pfp31_05,
    involvement_direct.advice_friends = pfp31_06,
    involvement_direct.advice_worries = pfp31_07,
    involvement_direct.activity_sport = pfp31_08,
    involvement_direct.activity_entertainment = pfp31_09,
    involvement_direct.activity_news = pfp31_10,
    involvement_direct.activity_cultural = pfp31_11,
    involvement_direct.activity_community = pfp31_12,
    involvement_direct.activity_museum = pfp31_13,
    involvement_direct.activity_theater = pfp31_14,
    involvement_indirect.informs = pfp32_1,
    involvement_indirect.engagement = pfp32_2,
    involvement_indirect.communication = pfp32_3,
    involvement_indirect.grades = pfp32_4,
    involvement_indirect.meetings = pfp32_5,
    preschool = pfp33,
    preschool.time = pfp34,
    grades.language = pfp35,
    grades.math = pfp36,
    retention.2 = pfp37,
    relocated = pfp38,
    relocate.will = pfp39,
    recolate.motive = pfp40,
    exp_education = pfp41
  ) %>%
  group_by(cod_mod7, anexo, seccion, cod_est) %>%
  mutate(ise_assets.auto = case_when(
    ise_assets.auto == "Sí" | drop_ise_assets.camioneta == "Sí" ~ "1",
    is.na(ise_assets.auto) & is.na(drop_ise_assets.camioneta) ~ NA_character_,
    TRUE ~ "0"
  ))

# 2do de Secundaria

form_2015_2s %<>%
  rename(
    cod_est = cod_al,
    idioma_hogar.mother = esp01,
    education.mother = esp02,
    idioma_hogar.father = esp03,
    education.father = esp04,
    involvement_direct.homework_speak = esp05_01,
    involvement_direct.homework_help = esp05_02,
    involvement_direct.homework_explain = esp05_03,
    involvement_direct.check_performance = esp05_04,
    involvement_direct.advice_books = esp05_05,
    involvement_direct.advice_performance = esp05_06,
    involvement_direct.advice_friends = esp05_07,
    involvement_direct.advice_worries = esp05_08,
    involvement_direct.activity_sport = esp05_09,
    involvement_direct.activity_entertainment = esp05_10,
    involvement_direct.activity_news = esp05_11,
    involvement_direct.activity_cultural = esp05_12,
    involvement_direct.activity_community = esp05_13,
    involvement_direct.activity_museum = esp05_14,
    involvement_direct.activity_theater = esp05_15,
    hogar.mother = esp06_1,
    hogar.father = esp06_2,
    hogar.abuelos = esp06_3,
    hogar.hermanos = esp06_4,
    hogar.tios = esp06_5,
    hogar.familiares = esp06_6,
    hogar.nofamiliares = esp06_7,
    n.hermanos = esp07,
    household.size = esp08,
    household.rooms = esp09,
    ise_house.wall = esp10,
    ise_house.roof = esp11,
    ise_house.floor = esp12,
    ise_utilities.water = esp13,
    ise_utilities.sewage = esp14,
    ise_utilities.light = esp15,
    cocina = esp16,
    ise_assets.radio = esp17_01,
    ise_assets.licuadora = esp17_02,
    ise_assets.plancha = esp17_03,
    ise_assets.tv = esp17_04,
    ise_other.tv_cc = esp17_05,
    ise_assets.reproductor = esp17_06,
    ise_other.telefono = esp17_07,
    ise_assets.celular = esp17_08,
    ise_other.datos_moviles = esp17_09,
    ise_other.internet = esp17_10,
    ise_assets.pc = esp17_11,
    ise_assets.laptop = esp17_12,
    ise_assets.tablet = esp17_13,
    ise_assets.sonido = esp17_14,
    ise_assets.consola = esp17_15,
    ise_assets.microondas = esp17_16,
    ise_assets.refigerador = esp17_17,
    ise_assets.lavadora = esp17_18,
    ise_assets.moto = esp17_19,
    ise_assets.auto = esp17_20,
    drop_ise_assets.camioneta = esp17_21,
    uso.moto = esp18_1,
    uso.auto = esp18_2,
    uso.camioneta = esp18_3,
    estudio.espacio = esp19,
    estudio.tranquilo = esp20_1,
    estudio.luz = esp20_2,
    estudio.muebles = esp20_3,
    estudio.estante = esp20_4,
    estudio.pc = esp20_5,
    books.n = esp21,
    books.school = esp22_1,
    books.encyclopedia = esp22_2,
    books.specialized = esp22_3,
    books.literature = esp22_4,
    age = esp23,
    idioma_materno = esp24,
    preschool = esp25,
    grades.language = esp26,
    grades.math = esp27,
    retention.2 = esp28_1,
    retention.3 = esp28_2,
    retention.4 = esp28_3,
    retention.5 = esp28_4,
    retention.6 = esp28_5,
    retention.7 = esp28_6,
    retention.8 = esp28_7,
    translado = esp29,
    idioma.espanol = esp30_1,
    idioma.quechua = esp30_2,
    idioma.aimara = esp30_3,
    idioma.amazonico = esp30_4,
    idioma.extranjero = esp30_5,
    exp_education = esp31,
    perceptions.understand_math = esp32_01,
    perceptions.learning_math = esp32_02,
    perceptions.comprenhension_math = esp32_03,
    perceptions.confidence_math = esp32_04,
    perceptions.istutor_math = esp32_05,
    perceptions.neednohelp_math = esp32_06,
    perceptions.pass_math = esp32_07,
    perceptions.talent_math = esp32_08,
    perceptions.motivation_math = esp32_09,
    perceptions.feelcompetent_math = esp32_10,
    perceptions.motivation_language = esp32_11,
    perceptions.understand_language = esp32_12,
    perceptions.learning_language = esp32_13,
    perceptions.neednohelp_language = esp32_14,
    perceptions.confidence_language = esp32_15,
    perceptions.istutor_language = esp32_16,
    perceptions.feelcompetent_language = esp32_17,
    perceptions.comprenhension_language = esp32_18,
    perceptions.talent_language = esp32_19,
    perceptions.pass_language = esp32_20,
    quit = esp33,
    quit.boring = esp34_1,
    quit.hard = esp34_2,
    quit.useless = esp34_3,
    quit.work = esp34_4,
    quit.family = esp34_5,
    quit.mates = esp34_6,
    quit.distance = esp34_7,
    school.explain_goals = esp35_01,
    school.reinforce_topics = esp35_02,
    school.applied_examples = esp35_03,
    school.multimedia_learning = esp35_04,
    school.interconnections = esp35_05,
    school.prior_knowledge = esp35_06,
    school.lack_deepness = esp35_07,
    school.argument_ideas = esp35_08,
    school.exact_answers = esp35_09,
    school.check_learning = esp35_10,
    school.confirm_all_participate = esp35_11,
    school.feedback = esp35_12,
    school.positive_feedback = esp35_13,
    school.correct_ontime = esp35_14,
    school.learning_suggestions = esp35_15,
    school.mention_learning_objectives = esp35_16,
    school.let_others_disturb = esp36_01,
    school.help_conflicts = esp36_02,
    school.let_misbehave = esp36_03,
    school.explain_good_behavior = esp36_04,
    school.shout_misbehave = esp36_05,
    school.incentivize = esp36_06,
    school.extra_help = esp36_07,
    school.congratulate = esp36_08,
    school.worry_welfare = esp36_09,
    school.humilliate = esp36_10,
    school.listen_to_me = esp36_11,
    school.explain_kindly = esp36_12,
    school.respect_opinions = esp36_13,
    school.conflict_btwn_teachers_students = esp36_14,
    school.good_relation_teachers_students = esp36_15,
    school.public_derision = esp36_16,
    school.tell_to_help_others = esp36_17,
    school.tell_to_be_friendly = esp36_18,
    school.feel_akward = esp36_19,
    school.tell_to_respect_mates = esp36_20,
    school.accept_bullying= esp36_21
  ) %>%
  group_by(cod_mod7, anexo, seccion, cod_est) %>%
  mutate(ise_assets.auto = case_when(
    ise_assets.auto == "Sí" | drop_ise_assets.camioneta == "Sí" ~ "1",
    is.na(ise_assets.auto) & is.na(drop_ise_assets.camioneta) ~ NA_character_,
    TRUE ~ "0"
  ))

## ECE 2016
# 2do de Primaria

form_2016_2p  %<>%
  rename(
    seccion = ID_seccion,
    cod_est = cor_est,
    guardian.sex = pa_01,
    guardian = pa_02,
    age.mother = pa_03,
    idioma_nativo.mother = pa_04,
    idioma_hogar.mother = pa_05,
    education.mother = pa_06,
    age.father = pa_07,
    idioma_nativo.father = pa_08,
    idioma_hogar.father = pa_09,
    education.father = pa_10,
    household.size = pa_11,
    household.rooms = pa_12,
    ise_house.wall = pa_13,
    ise_house.roof = pa_14,
    ise_house.floor = pa_15,
    ise_utilities.water = pa_16,
    ise_utilities.sewage = pa_17,
    ise_utilities.light = pa_18,
    ise_assets.radio = pa_19_01,
    ise_assets.licuadora = pa_19_02,
    ise_assets.plancha = pa_19_03,
    ise_assets.tv = pa_19_04,
    drop_ise_assets.celular = pa_19_05,
    ise_assets.reproductor = pa_19_06,
    ise_assets.pc = pa_19_07,
    ise_assets.laptop = pa_19_08,
    ise_assets.tablet = pa_19_09,
    ise_assets.sonido = pa_19_10,
    ise_assets.consola = pa_19_11,
    ise_assets.microondas = pa_19_12,
    ise_assets.refigerador = pa_19_13,
    ise_assets.lavadora = pa_19_14,
    ise_assets.moto = pa_19_15,
    ise_assets.auto = pa_19_16,
    ise_other.telefono = pa_19_17,
    ise_assets.celular = pa_19_18,
    ise_other.datos_moviles = pa_19_19,
    ise_other.internet = pa_19_20,
    ise_other.tv_cc = pa_19_21,
    salud.sis = pa_20_01,
    salud.minsa = pa_20_02,
    salud.essalud = pa_20_03,
    salud.eps = pa_20_04,
    salud.particular = pa_20_05,
    estudio.muebles = pa_21_01,
    estudio.espacio = pa_21_02,
    estudio.diccionario = pa_21_03,
    estudio.pc = pa_21_04,
    estudio.programas = pa_21_05,
    books.school = pa_22_01,
    books.encyclopedia = pa_22_02,
    books.specialized = pa_22_03,
    books.literature = pa_22_04,
    books.n = pa_23,
    preschool = pa_24,
    preschool.time = pa_25,
    retention.2 = pa_26,
    perceptions.boys_better_girls = pa_27_01,
    perceptions.girls_better_boys = pa_27_02,
    perceptions.boys_talent = pa_27_03,
    perceptions.girls_talent = pa_27_04,
    perceptions.talent_math = pa_28_01,
    perceptions.passion_math = pa_28_02,
    perceptions.effort_math = pa_28_03,
    perceptions.teacher_math = pa_28_04,
    perceptions.luck_math = pa_28_05,
    perceptions.support_math = pa_28_06,
    perceptions.talent_language = pa_29_01,
    perceptions.passion_language = pa_29_02,
    perceptions.effort_language = pa_29_03,
    perceptions.teacher_language = pa_29_04,
    perceptions.luck_language = pa_29_05,
    perceptions.support_language = pa_29_06,
    habilidad.matematica = pa_30,
    futuro.matematica = pa_31,
    grades.math = pa_32,
    habilidad.comunicacion = pa_33,
    futuro.comunicacion = pa_34,
    grades.language = pa_35,
    exp_education = pa_36,
    school.location = pa_37,
    school.transport = pa_38,
    school.distance = pa_39
  )

## OJO HACER MERGE CON AUTO CAMIONETA (EQUIPAMENTO.AUTO)

# 4to de Primaria

form_2016_4p %<>%
  rename(
    seccion = ID_seccion,
    cod_est = cor_est,
    guardian.sex = pa_01,
    guardian = pa_02,
    age.mother = pa_03,
    idioma_nativo.mother = pa_04,
    idioma_hogar.mother = pa_05,
    education.mother = pa_06,
    age.father = pa_07,
    idioma_nativo.father = pa_08,
    idioma_hogar.father = pa_09,
    education.father = pa_10,
    household.size = pa_11,
    household.rooms = pa_12,
    ise_house.wall = pa_13,
    ise_house.roof = pa_14,
    ise_house.floor = pa_15,
    ise_utilities.water = pa_16,
    ise_utilities.sewage = pa_17,
    ise_utilities.light = pa_18,
    ise_assets.radio = pa_19_01,
    ise_assets.licuadora = pa_19_02,
    ise_assets.plancha = pa_19_03,
    ise_assets.tv = pa_19_04,
    ise_assets.celular = pa_19_05,
    ise_assets.reproductor = pa_19_06,
    ise_assets.pc = pa_19_07,
    ise_assets.laptop = pa_19_08,
    ise_assets.tablet = pa_19_09,
    ise_assets.sonido = pa_19_10,
    ise_assets.consola = pa_19_11,
    ise_assets.microondas = pa_19_12,
    ise_assets.refigerador = pa_19_13,
    ise_assets.lavadora = pa_19_14,
    ise_assets.moto = pa_19_15,
    ise_assets.auto = pa_19_16,
    ise_other.telefono = pa_19_17,
    drop_ise_assets.celular = pa_19_18,
    ise_other.datos_moviles = pa_19_19,
    ise_other.internet = pa_19_20,
    ise_other.tv_cc = pa_19_21,
    salud.sis = pa_20_01,
    salud.minsa = pa_20_02,
    salud.essalud = pa_20_03,
    salud.eps = pa_20_04,
    salud.particular = pa_20_05,
    estudio.muebles = pa_21_01,
    estudio.espacio = pa_21_02,
    estudio.diccionario = pa_21_03,
    estudio.pc = pa_21_04,
    estudio.programas = pa_21_05,
    books.school = pa_22_01,
    books.encyclopedia = pa_22_02,
    books.specialized = pa_22_03,
    books.literature = pa_22_04,
    books.n = pa_23,
    preschool = pa_24,
    preschool.time = pa_25,
    retention = pa_26,
    grades.math = pa_27,
    grades.language = pa_28,
    exp_education = pa_29
  ) 

# 2do de Secundaria

form_2016_2s %<>%
  rename(
    seccion = ID_seccion,
    cod_est = cor_est,
    idioma_hogar.mother = e1_01,
    education.mother = e1_02,
    idioma_hogar.father = e1_03,
    education.father = e1_04,
    household.size = e1_05,
    household.rooms = e1_06,
    ise_house.wall = e1_07,
    ise_house.roof = e1_08,
    ise_house.floor = e1_09,
    ise_utilities.water = e1_10,
    ise_utilities.sewage = e1_11,
    ise_utilities.light = e1_12,
    ise_assets.radio = e1_13_01,
    ise_assets.licuadora = e1_13_02,
    ise_assets.plancha = e1_13_03,
    ise_assets.tv = e1_13_04,
    ise_assets.celular = e1_13_05,
    ise_assets.reproductor = e1_13_06,
    ise_assets.pc = e1_13_07,
    ise_assets.laptop = e1_13_08,
    ise_assets.tablet = e1_13_09,
    ise_assets.sonido = e1_13_10,
    ise_assets.consola = e1_13_11,
    ise_assets.microondas = e1_13_12,
    ise_assets.refigerador = e1_13_13,
    ise_assets.lavadora = e1_13_14,
    ise_assets.moto = e1_13_15,
    ise_assets.auto = e1_13_16,
    ise_other.telefono = e1_13_17,
    drop_ise_assets.celular = e1_13_18,
    ise_other.datos_moviles = e1_13_19,
    ise_other.internet = e1_13_20,
    ise_other.tv_cc = e1_13_21,
    estudio.muebles = e1_14_01,
    estudio.espacio = e1_14_02,
    estudio.diccionario = e1_14_03,
    estudio.pc = e1_14_04,
    estudio.programas = e1_14_05,
    books.n = e1_15,
    books.school = e1_16_01,
    books.encyclopedia = e1_16_02,
    books.specialized = e1_16_03,
    books.literature = e1_16_04,
    idioma_materno = e1_17,
    preschool = e1_18,
    grades.math = e1_19,
    grades.language = e1_20,
    school.permanencia = e1_21,
    retention = e1_22,
    exp_education = e1_23,
    school.explain_goals = e1_24_01,
    school.reinforce_topics = e1_24_02,
    school.applied_examples = e1_24_03,
    school.multimedia_learning = e1_24_04,
    school.interconnections = e1_24_05,
    school.prior_knowledge = e1_24_06,
    school.lack_deepness = e1_24_07,
    school.argument_ideas = e1_24_08,
    school.exact_answers = e1_24_09,
    school.check_learning = e1_24_10,
    school.confirm_all_participate = e1_24_11,
    school.feedback = e1_24_12,
    school.positive_feedback = e1_24_13,
    school.correct_ontime = e1_24_14,
    school.learning_suggestions = e1_24_15,
    school.mention_learning_objectives = e1_24_16,
    profesor.amenaza = e1_25_01,
    companero.abuso_fisico = e1_25_02,
    companero.insulto = e1_25_03,
    profesor.insulto = e1_25_04,
    companero.robo = e1_25_05,
    profesor.abuso_fisico = e1_25_06,
    companero.amenaza = e1_25_07,
    school.students_obey = e1_26_01,
    school.students_know_rules = e1_26_02,
    school.teachers_fair = e1_26_03,
    school.let_others_disturb = e1_26_04, #(-1)
    school.respect_opinions = e1_26_05,
    school.principal_friendly = e1_26_06,
    school.classes_start_late = e1_26_07,
    school.rules_are_fair = e1_26_08,
    school.sanctions_are_enforced = e1_26_09,
    school.correct_those_who_offend = e1_26_10,
    school.conflict_btwn_teachers_students = e1_26_11, #(-1)
    school.mates_are_late = e1_26_12,
    school.good_relation_teachers_students = e1_26_13,
    school.shout_misbehave = e1_26_14, #(-1)
    school.feel_akward = e1_26_15, #(-1)
    school.care_about_delivering_homework_on_time = e1_26_16,
    school.tell_to_respect_mates = e1_26_17,
    school.teachers_follow_rules = e1_26_18,
    school.mates_bring_forbidden_objects = e1_26_19,
    school.worry_welfare = e1_26_20,
    school.accept_bullying = e1_26_21, #(-1)
    school.students_follow_rules = e1_26_22,
    school.mates_are_absent = e1_26_23,
    school.explain_good_behavior = e1_26_24, #(-1)
  ) 

## ECE 2018
# 4to de Primaria

form_2018_4p %<>%
  rename(
    seccion = ID_seccion,
    cod_est = cor_est,
    guardian.sex = p01,
    guardian = p02,
    ise_house.wall = p03,
    ise_house.roof = p04,
    ise_house.floor = p05,
    ise_utilities.water = p06,
    ise_utilities.sewage = p07,
    ise_utilities.light = p08,
    ise_assets.radio = p09_01,
    ise_assets.licuadora = p09_02,
    ise_assets.plancha = p09_03,
    ise_assets.tv = p09_04,
    ise_assets.celular = p09_05,
    ise_assets.reproductor = p09_06,
    ise_assets.pc = p09_07,
    ise_assets.laptop = p09_08,
    ise_assets.tablet = p09_09,
    ise_assets.sonido = p09_10,
    ise_assets.consola = p09_11,
    ise_assets.microondas = p09_12,
    ise_assets.refigerador = p09_13,
    ise_assets.lavadora = p09_14,
    ise_assets.moto = p09_15,
    ise_assets.auto = p09_16,
    ise_other.telefono = p09_17,
    drop_ise_assets.celular = p09_18,
    ise_other.datos_moviles = p09_19,
    ise_other.internet = p09_20,
    ise_other.tv_cc = p09_21,
    age.father = p10,
    idioma_nativo.father = p11,
    idioma_hogar.father = p12,
    education.father = p13,
    age.mother = p14,
    idioma_nativo.mother = p15,
    idioma_hogar.mother = p16,
    education.mother = p17,
    school.distance = p18_01,
    preschool.distance = p18_02,
    otherschool.distance = p18_03,
    secundaria.distance = p18_04,
    motivo.distance = p19_01,
    motivo.infraestructura = p19_02,
    motivo.amigos = p19_03,
    motivo.religion = p19_04,
    motivo.valores = p19_05,
    motivo.excelencia = p19_06,
    motivo.resultados = p19_07,
    motivo.homofilia = p19_08,
    motivo.economia = p19_09,
    motivo.unica = p19_10,
    motivo.ingreso = p19_11,
    motivo.hermanos = p19_12,
    motivo.disciplina = p19_13,
    motivo.otro = p19_14,
    school.transport = p20_01,
    preschool.transport = p20_02,
    otherschool.transport = p20_03,
    secundaria.transport = p20_04,
    school.charlas = p21_01,
    school.rendicion = p21_02,
    school.rendimiento = p21_03,
    school.aprendizajes = p21_04,
    school.informacion = p21_05,
    school.extracurriculares = p21_06,
    school.actividades_otros = p21_07,
    school.concursos = p22_01,
    school.campeonatos = p22_02,
    school.presentaciones = p22_03,
    school.desfiles = p22_04,
    school.talleres_letras = p22_05,
    school.talleres_artes = p22_06,
    school.refuerzos = p22_07,
    school.n_tareas = p23_01,
    school.div_tareas = p23_02,
    school.pedagogia = p23_03,
    school.div_evaluacion = p23_04,
    school.n_evaluacion = p23_05,
    school.n_materiales = p23_06,
    school.n_books = p23_07,
    school.respeto = p24_01,
    school.pedagogia_respeto = p24_02,
    school.reprension = p24_03,
    school.docente_normas = p24_04,
    school.docente_agfisica = p24_05,
    school.docente_agverbal = p24_06,
    school.normas = p24_07,
    perceptions.boys_better_girls = p25_01,
    perceptions.girls_better_boys = p25_02,
    perceptions.boys_easier_girls = p25_03,
    perceptions.girls_easier_boys = p25_04,
    perceptions.boys_talent = p25_05,
    perceptions.girls_talent = p25_06,
    matematica.talento = p26_01,
    matematica.gusto = p26_02,
    matematica.esfuerzo = p26_03,
    matematica.suerte = p26_04,
    matematica.apoyo = p26_05,
    exp_education = p27,
    preschool = p28,
    preschool.time = p29,
    retention.2 = p30_01,
    retention.3 = p30_02,
    retention.4 = p30_03,
    plan_lector.info = p31,
    plan_lector.lectura = p32_01,
    plan_lector.apoyo = p32_02,
    plan_lector.seleccion = p32_03,
    plan_lector.adquisicion = p32_04,
    plan_lector.evaluacion = p32_05,
  ) 

## ECE 2018
# 2do de Secundaria

form_2018_2s %<>%
  rename(
    seccion = ID_seccion,
    cod_est = cor_est,
    idioma_hogar.mother = p01,
    education.mother = p02,
    idioma_hogar.father = p03,
    education.father = p04,
    household.size = p05,
    ise_house.wall = p06,
    ise_house.roof = p07,
    ise_house.floor = p08,
    ise_utilities.water = p09,
    ise_utilities.sewage = p10,
    ise_utilities.light = p11,
    ise_assets.radio = p12_01,
    ise_assets.licuadora = p12_02,
    ise_assets.plancha = p12_03,
    ise_assets.tv = p12_04,
    ise_assets.celular = p12_05,
    ise_assets.reproductor = p12_06,
    ise_assets.pc = p12_07,
    ise_assets.laptop = p12_08,
    ise_assets.tablet = p12_09,
    ise_assets.sonido = p12_10,
    ise_assets.consola = p12_11,
    ise_assets.microondas = p12_12,
    ise_assets.refigerador = p12_13,
    ise_assets.lavadora = p12_14,
    ise_assets.moto = p12_15,
    ise_assets.auto = p12_16,
    ise_other.telefono = p12_17,
    drop_ise_assets.celular = p12_18,
    ise_other.datos_moviles = p12_19,
    ise_other.internet = p12_20,
    ise_other.tv_cc = p12_21,
    school.explain_goals = p13_01,
    school.reinforce_topics = p13_02,
    school.applied_examples = p13_03,
    school.multimedia_learning = p13_04,
    school.interconnections = p13_05,
    school.prior_knowledge = p13_06,
    school.lack_deepness = p13_07,
    school.argument_ideas = p13_08,
    school.exact_answers = p13_09,
    school.check_learning = p13_10,
    school.confirm_all_participate = p13_11,
    school.feedback = p13_12,
    school.positive_feedback = p13_13,
    school.correct_ontime = p13_14,
    school.learning_suggestions = p13_15,
    school.mention_learning_objectives = p13_16,
    profesor.amenaza = p14_01,
    profesor.insulto = p14_02,
    profesor.soborno = p14_03,
    profesor.ignorar = p14_04,
    profesor.abuso_fisico = p14_05,
    profesor.abuso_fisico_agr = p14_06,
    profesor.humillacion = p14_07,
    profesor.escarnio = p14_08,
    companero.amenaza = p15_01,
    companero.abuso_fisico = p15_02,
    companero.insulto = p15_03,
    companero.robo = p15_04,
    companero.chisme = p15_05,
    companero.exclusion = p15_06,
    companero.gritos = p15_07,
    companero.humillacion = p15_08,
    discriminacion.piel = p16_01,
    discriminacion.origen = p16_02,
    discriminacion.habla = p16_03,
    discriminacion.lgtbi = p16_04,
    discriminacion.fisico = p16_05,
    discriminacion.discapacidad = p16_06,
    discriminacion.religion = p16_07,
    discriminacion.pobreza = p16_08,
    discriminacion.sexual = p16_09,
    discriminacion.rendimiento = p16_10,
    discriminacion.burla = p16_11,
    afirmacion_a = p17_01,
    afirmacion_b = p17_02,
    afirmacion_c = p17_03,
    afirmacion_d = p17_04,
    afirmacion_e = p17_05,
    afirmacion_f = p17_06,
    afirmacion_g = p18_01,
    afirmacion_h = p18_02,
    afirmacion_i = p18_03,
    afirmacion_j = p18_04,
    afirmacion_k = p18_05,
    afirmacion_l = p18_06,
    afirmacion_m = p18_07,
    afirmacion_n = p19_01,
    afirmacion_o = p19_02,
    afirmacion_p = p19_03,
    afirmacion_q = p19_04,
    afirmacion_r = p19_05,
    idioma_materno = p20,
    preschool = p21,
    retention = p22,
    exp_education = p23,
    habitos_1 = p24_01,
    habitos_2 = p24_02,
    habitos_3 = p24_03,
    habitos_4 = p24_04,
    habitos_5 = p24_05,
    habitos_6 = p24_06,
    habitos_7 = p24_07,
    habitos_8 = p24_08,
    habitos_9 = p24_09,
    habitos_10 = p24_10,
    habitos_11 = p24_11,
    habitos_12 = p24_12,
    habitos_13 = p24_13,
    habitos_14 = p24_14,
    habitos_15 = p24_15,
    habitos_16 = p24_16,
  ) 

perra1 <- form_2015_2p %>%
  dplyr::select(cod_mod7, anexo, seccion, cod_est, guardian, #Basic match
                starts_with("preschool"), starts_with("retention"), starts_with("grades"), exp_education, #Education
                matches("(.mother)|(.father)"), matches("household.size"), starts_with("income"), starts_with("ise"), #Economic
                starts_with("involvement"), starts_with("perception"), starts_with("books"), matches("school.(distance)(time)")) %>% #Other
  mutate(across(everything(), as.character))

perra2 <- form_2016_2p %>%
  dplyr::select(cod_mod7, anexo, seccion, cod_est, guardian, #Basic match
                starts_with("preschool"), starts_with("retention"), starts_with("grades"), exp_education, #Education
                matches("(.mother)|(.father)"), matches("household.size"), starts_with("income"), starts_with("ise"), #Economic
                starts_with("involvement"), starts_with("perception"), starts_with("books"), matches("school.(distance)(time)")) %>% #Other
  mutate(across(everything(), as.character))

perra3 <- form_2016_4p %>%
  dplyr::select(cod_mod7, anexo, seccion, cod_est, guardian, #Basic match
                starts_with("preschool"), starts_with("retention"), starts_with("grades"), exp_education, #Education
                matches("(.mother)|(.father)"), matches("household.size"), starts_with("income"), starts_with("ise"), #Economic
                starts_with("involvement"), starts_with("perception"), starts_with("books"), matches("school.(distance)(time)")) %>% #Other
  mutate(across(everything(), as.character))

perra4 <- form_2018_4p %>%
  dplyr::select(cod_mod7, anexo, seccion, cod_est, guardian, #Basic match
                starts_with("preschool"), starts_with("retention"), starts_with("grades"), exp_education, #Education
                matches("(.mother)|(.father)"), matches("household.size"), starts_with("income"), starts_with("ise"), #Economic
                starts_with("involvement"), starts_with("perception"), starts_with("books"), matches("school.(distance)(time)")) %>% #Other
  mutate(across(everything(), as.character))

gonorrea <- bind_rows(perra1, perra2, perra3, perra4)
names(gonorrea)

form_2018_2s %>% slice(1) %>% write_csv("nombres.csv")

ls(pattern = "(perra)|(form_2015_2s)") %>%
  map(~ rlang::parse_expr(.x) %>% eval()) %>%
  map(names) %>%
  reduce(intersect)

### Treatment

treatment <- ls(pattern = "^form_") %>%
  include_name() %>% 
  rename(cod_mod = cod_mod7) %>%
  mutate(
    cod_mod = as.integer(cod_mod),
    anexo = as.integer(anexo),
    cod_est = as.integer(cod_est),
    tipo_eva = case_when(
      tipo_eva == "2p" ~ 1L,
      tipo_eva == "4p" ~ 2L,
      tipo_eva == "2s" ~ 3L),
    seccion = str_to_lower(seccion),
    preschool = str_sub(preschool, 1, 5),
    preschool = case_when(
      str_detect(preschool, "No") ~ 0L,
      TRUE ~ 1L)
    )

dbWriteTable(db_conn, name = "ece_treatment", treatment)

#### TREATMENT

inconsistencies <- tbl(db_conn, "test_scores") %>%
  inner_join(tbl(db_conn, "matriculation")) %>%
  inner_join(tbl(db_conn, "ece_treatment")) %>% 
  inner_join(tbl(db_conn, "student_id")) %>%
  group_by(student_id) %>%
  mutate(preschool_check = sum(preschool, na.rm = TRUE)) %>%
  filter(preschool_check != n(), preschool_check != 0) %>%
  collect()
